// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://aivayoleogjvgpkvxmkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpdmF5b2xlb2dqdmdwa3Z4bWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNjkwNzUsImV4cCI6MjA3MzY0NTA3NX0.vPP3sqVWTxgNNV_Du1qvnE6C9fg1-sa074Ap-yTP-XI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);